### ISSUE TITLE
Wrong namespace used

### ISSUE THREAD

**Issue by dinamic** [jiminny/oauth2-pipedrive#2]
Caused by: https://github.com/jiminny/oauth2-pipedrive/pull/1

The `Exception` namespace was renamed to `Exceptions`, but the usages were never updated.

Here's one such usage, but there could be more:
- https://github.com/jiminny/oauth2-pipedrive/blob/a0c78c5c5a236e573d2c0cbdfe1b1bd022010b67/src/Pipedrive.php#L6

**Comment by vladTemp** [comment]
Fixes in https://github.com/jiminny/oauth2-pipedrive/pull/3
